before_install:
   - sudo add-apt-repository -y ppa:kubuntu-ppa/backports 
   - sudo apt-get update
language: perl
install:
  - cpanm -nq Perl::Tidy Data::Dump JSON
  - sudo apt-get install libopencv-dev libtheora-dev libcv-dev libhighgui-dev libdata-dump-perl libjson-perl tesseract-ocr
script:
  - ./tools/tidy --check
  - sh autogen.sh 
  - ./configure
  - make && make check

