codecov:
  branch: master
comment:
  behavior: default
  require_changes: true
coverage:
  range: 60..95
  round: down
  precision: 2
  status:
    changes: false
    project:
      default:
        target: 62.2
        threshold: 0.1
    patch:
      default:
        branches: null
fixes:
  - "/opt/::"
